### ISSUE TITLE
Problem with styled-components

### ISSUE THREAD

**Issue by NewOldMax** [xuopled/react-google-places-suggest#22] opened 2018-02-07 08:41 UTC
Hi,
I've installed `react-google-places-suggest` and `react-google-maps-loader`, but when I'm trying to build them, I'm getting error `Cannot find module 'styled-components' from 'node_modules/react-google-places-suggest/lib'`.
I don't see any `styled-components` dependency from `react-google-places-suggest` (and see in `react-google-maps-loader` but it's installed locally for it) so it's missing.
Do I miss something?

Btw it's not obvious to install `react-google-maps-loader` to make work `react-google-places-suggest`. For my opinion, better to move it to `dependencies` section. What do you think? It can save us from having unsupported combinations of libraries. And it can be exposed something like this:
````javascript
// index.js
import GoogleMapsLoader from 'react-google-maps-loader';
import GooglePlacesSuggest from './GooglePlacesSuggest';

export {
  GoogleMapsLoader,
  GooglePlacesSuggest ,
};

// some user file
import { GoogleMapsLoader, GooglePlacesSuggest } from 'react-google-places-suggest';

````

**Comment by xuopled** [comment] 2018-02-07 10:34
Hi @NewOldMax Thank you for reporting this. It seems like a big bug. I will fix it

**Comment by xuopled** [comment] 2018-02-07 11:52
@NewOldMax I just release `v3.3.1`. Could you check if the problem is gone for you ?
Thank you

**Comment by NewOldMax** [comment] 2018-02-07 11:59
Yes, it works now

**Comment by xuopled** [comment] 2018-02-07 12:16
Great ! I close the issue then

**Closed by xuopled** 2018-02-07 12:16 UTC
